//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaPremiera.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auth
    {
        public int Auth_ID { get; set; }
        public int Pincode { get; set; }
        public int Role_ID { get; set; }
    
        public virtual Role Role { get; set; }
    }
}
