//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaPremiera.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Order_ID { get; set; }
        public System.DateTime DateBuy { get; set; }
        public int Film_ID { get; set; }
        public System.DateTime DateSession { get; set; }
        public int PriceList_ID { get; set; }
        public int Count { get; set; }
        public decimal CheckSum { get; set; }
        public int PaymentType_ID { get; set; }
        public string Note { get; set; }
    
        public virtual Film Film { get; set; }
        public virtual PaymentType PaymentType { get; set; }
        public virtual PriceList PriceList { get; set; }
    }
}
